# Generated by Django 4.2 on 2023-10-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_advancestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancestats',
            name='player_efficiency_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
